### ISSUE TITLE
感觉可以把`cache`拎出来写一篇的,主要写文件缓存`type: filesystem`就好了:robot:

### ISSUE THREAD

**Issue by Jim-jw** [fz6m/webpack5-boilerplate-book#1]
wp5通过配置`cache`构建速度变快经常拿出来说的，升级wp5基本上也是必配的，文件缓存时候把`name`跟`buildDependencies`搞清楚配置好你说的corner case基本上不会发生:monkey:

**Comment by fz6m** [comment]
我觉得你说的有道理，已增加此部分内容，阿里嘎多
